#!/usr/bin/env python3
"""
Build the aux battle-text catalog from an index-aligned Korean array.

READ-ONLY with respect to ROMs.

Scope is deliberately narrow, and every narrowing is a safety property:

* **contiguous blocks only** — the record set comes from
  ``tools/find_aux_text_blocks.py``, which keeps only runs of consecutive records
  that all decode coherently. Per-record filters do not work here: a
  character-class test passes ~16,000 aux records and most are graphics bytes that
  happen to decode to kana. Real strings tile; garbage does not sustain a run.
* **provably text-initial only** — a record is eligible only if its first byte is
  a dictionary token or a 2-byte character lead. Many aux records begin with a
  single-byte code that is a speaker/portrait id rendered as a stray glyph
  (``5a``→``カ``, ``5e``→``コ``, ``32``→``き``), and it cannot be told apart from real
  leading text (``80``→``機`` in ``機銃座は……`` is genuine). Rather than guess, records
  with an ambiguous leading byte are excluded — 3,158 of them.
* **still Japanese on the target**, and unchanged from the original.

That leaves the mission dialogue in bank 59, the skill/ability descriptions in
5C and the pilot battle voice lines in 5D/5E.

As with the name75 lexicon, the Japanese side is never retyped: ``--emit`` writes
the exact ordered unique texts and the translator supplies a parallel array.
Length mismatch is a hard error.

Modes:
  --emit   → out/script/aux_text_ordered.json (+ .txt)
  --build  → data/aux_text_ko.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import List, Sequence

ROOT = Path(__file__).resolve().parents[1]

DEFAULT_ELIGIBLE = ROOT / "out/script/aux_block_eligible.json"
DEFAULT_ORDERED = ROOT / "out/script/aux_text_ordered.json"
DEFAULT_VALUES = ROOT / "data/aux_text_ko_values.json"
DEFAULT_OUT = ROOT / "data/aux_text_ko.json"


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--eligible", type=Path, default=DEFAULT_ELIGIBLE)
    ap.add_argument("--ordered", type=Path, default=DEFAULT_ORDERED)
    ap.add_argument("--values", type=Path, default=DEFAULT_VALUES)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--emit", action="store_true")
    ap.add_argument("--build", action="store_true")
    args = ap.parse_args(argv)

    if args.out.suffix.lower() == ".wsc":
        raise SystemExit("refusing to write a .wsc")

    blob = json.loads(args.eligible.read_text(encoding="utf-8"))
    rows: List[dict] = blob["unique"]

    if args.emit:
        args.ordered.parent.mkdir(parents=True, exist_ok=True)
        args.ordered.write_text(
            json.dumps(
                {
                    "_note": "exact ordered unique aux texts; supply a parallel "
                    "'ordered_ko' array of the same length in "
                    "data/aux_text_ko_values.json (empty = leave Japanese)",
                    "count": len(rows),
                    "texts": [r["jp"] for r in rows],
                    "sites": {r["jp"]: r["sites"] for r in rows},
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        args.ordered.with_suffix(".txt").write_text(
            "\n".join(
                f"{i}\t{len(r['sites'])}\t{r['jp']}" for i, r in enumerate(rows)
            )
            + "\n",
            encoding="utf-8",
        )
        print(f"emitted {len(rows)} unique texts → {args.ordered}")
        print(f"numbered list → {args.ordered.with_suffix('.txt')}")
        return 0

    if not args.build:
        raise SystemExit("pick --emit or --build")

    texts = json.loads(args.ordered.read_text(encoding="utf-8"))["texts"]
    spec = json.loads(args.values.read_text(encoding="utf-8"))
    ko_list = spec.get("ordered_ko") or []
    if len(ko_list) != len(texts):
        raise SystemExit(
            f"length mismatch: {len(texts)} texts vs {len(ko_list)} translations. "
            "A shifted array mistranslates every line after the shift — refusing."
        )

    entries = [
        {"jp": jp, "ko": ko.strip()}
        for jp, ko in zip(texts, ko_list)
        if ko and ko.strip()
    ]
    payload = {
        "description": (
            "Aux battle text — mission dialogue (bank 59), skill/ability "
            "descriptions (5C) and pilot battle voice lines (5D/5E). Generated by "
            "tools/build_aux_catalog.py --build from data/aux_text_ko_values.json; "
            "do not hand-edit, edit the values file and rebuild."
        ),
        "_marker_note": (
            "marker is not declared here on purpose: the installed Hangul run "
            "marker is read from tools/hangul_marker.py."
        ),
        "generated_by": "tools/build_aux_catalog.py",
        "candidate_count": len(texts),
        "translated": len(entries),
        "untranslated": len(texts) - len(entries),
        "entries": entries,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(
        f"catalog: {len(entries)} translated / {len(texts)} texts "
        f"({len(texts) - len(entries)} left Japanese)"
    )
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
